# Site
repository: dannycastonguay/resume
# favicon: images/favicon.ico

# Personal info
name: Danny Castonguay
title: Product leader
email: danny@talented.app
website: www.dannycastonguay.com

# Social links
twitter_username: dannycast0nguay
github_username:  dannycastonguay
# dribbble_username: jekyll
# facebook_username: dannycastonguay
# flickr_username: jekyll
# instagram_username: 
linkedin_username: dannycastonguay
# pinterest_username: jekyll
youtube_username: dannycastonguay
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Founder of Talented.app. Exultant worker, father, and husband.

  I am most skilled in: <mark>business</mark>, <mark>software</mark>, and <mark>health</mark>.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in technology, design, sustainability, education, and finance, some of my other interests and hobbies are:
   - Muay Thai, Jiu Jitsu, Yoga
   - Meditation
   - Card, board, and video games
# Footer
footer_show_references: true

# Build settings
remote_theme: dannycastonguay/dannyresume

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
