# Site
repository: dannycastonguay/resume
# favicon: images/favicon.ico
google_analytics: UA-141196625-2

# Personal info
name: Danny Castonguay
title: Product leader
email: danny@talented.app
website: www.dannycastonguay.com

# Social links
twitter_username: dannycast0nguay
github_username:  dannycastonguay
# dribbble_username: jekyll
# facebook_username: dannycastonguay
# flickr_username: jekyll
# instagram_username: 
linkedin_username: dannycastonguay
# pinterest_username: jekyll
# youtube_username: dannycastonguay
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  I'm the founder of Talented.app and the co-Founder of Kalibrr.com. I'm a former McKinsey Expert Associate Partner. I'm a husband and father of three. I train Brazilian Jui-Jitsu 5 times a week and I don't compromise on sleep, nutrition, and meditation/relaxation. I challenge my teams, I create accountability structure, and I give a lot of (tough) love.

  Tools I like to use include: <mark>Gitlab</mark>, <mark>SKLearn</mark>, and <mark>Figma</mark>.

  I am most skilled in: <mark>Business</mark>, <mark>Product Management</mark>, and <mark>Team Health</mark>.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in technology, design, sustainability, education, and finance, some of my other interests and hobbies are:
   - Muay Thai, Jiu Jitsu, Yoga
   - Meditation
   - Card, board, and video games
# Footer
footer_show_references: true

# Build settings
remote_theme: dannycastonguay/dannyresume

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
